apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-initdb-config
data:
  initdb.sql: |
    CREATE DATABASE IF NOT EXISTS markit_test COLLATE 'utf8_general_ci';
    GRANT ALL PRIVILEGES ON markit_test.* TO 'markit'@'%';