apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-pv-volume
spec:
  storageClassName: standard
  capacity:
    storage: 300M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/markit/api-pv-volume/