apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-pv-claim
spec:
    storageClassName: standard
    volumeName: api-pv-volume
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 300M