apiVersion: v1
kind: ConfigMap
metadata:
  name: api-entrypoint-configmap
data:
  entrypoint.sh: |
    #! /bin/sh
    set -e
    composer install

    FILE=/var/www/html/vendor/autoload.php
    if [ ! -f "$FILE" ]; then
        composer dump-autoload --optimize
    fi

    find storage -type d -print0 | xargs -0 chmod 775
    find storage -type f -print0 | xargs -0 chmod 664