apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: markt-mariadb
  template:
    metadata:
      labels:
        app: markt-mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: root-password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: markt-password
        - name: MYSQL_USER
          value: markt
        - name: MYSQL_DATABASE
          value: markt
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/mysql
        - name: mariadb-initdb
          mountPath: /docker-entrypoint-initdb.d/
        resources:
            limits:
              cpu: 400m
              memory: 400Mi
            requests:
              cpu: 200m
              memory: 200Mi
      volumes:
      - name: datadir
        persistentVolumeClaim:
          claimName: mariadb-pv-claim
      - name: mariadb-initdb
        configMap:
          name: mariadb-initdb-config