apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
spec:
    storageClassName: standard
    volumeName: mariadb-pv-volume
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 300M