apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy: {}
  template:
    metadata:
      labels:
        app: api
    spec:
      restartPolicy: Always
      initContainers:
      - name: composer
        image: api:latest
        command: ['composer', 'install']
        workingDir: /var/www/html
      containers:
        - name: api
          image: api:latest
          command: ["php"]
          args: ["artisan", "octane:start"]
          workingDir: /var/www/html
          volumeMounts:
          - name: entrypoint
            mountPath: /home/bin
          env:
          - name: DB_HOST
            value: mariadb
          - name: DB_USERNAME
            value: markit
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: api-secrets
                key: mariadb-markit-password
          resources:
            limits:
              cpu: 800m
              memory: 800Mi
            requests:
              cpu: 400m
              memory: 400Mi
          ports:
            - containerPort: 8000
      volumes:
        - name: entrypoint
          configMap:
            name: api-entrypoint-configmap
            defaultMode: 0777
      